// Official SMTP presets. These talk to the provider you actually have an
// account with — not open relays, not SOCKS proxies.

export const SENDER_KINDS = [
  {
    id: 'smtp',
    label: 'SMTP',
    blurb: 'Any mail server you own (custom domain, transactional SMTP, VPS).',
  },
  {
    id: 'ovh',
    label: 'OVH',
    blurb: 'OVH / OVHcloud mailbox (smtp.mail.ovh.net).',
  },
  {
    id: 'webmail',
    label: 'Webmail',
    blurb: 'Gmail, Outlook, Yahoo, iCloud, Zoho — sign in with the mailbox SMTP.',
  },
  {
    id: 'japan',
    label: 'Japan mail',
    blurb: 'Yahoo! Mail Japan, Sakura, Xserver, Lolipop, GMO, and other JP hosts.',
  },
  {
    id: 'smtp_sms',
    label: 'SMTP → SMS',
    blurb: 'Email-to-SMS carrier gateway. Recipients need a phone number.',
  },
  {
    id: 'office365',
    label: 'Office 365',
    blurb: 'Your Microsoft 365 tenant via Graph sendMail or smtp.office365.com SMTP AUTH.',
  },
];

export const SMTP_PRESETS = [
  {
    id: 'custom',
    kind: 'smtp',
    label: 'Custom SMTP',
    host: '',
    port: 587,
    secure: false,
    hint: 'Use the host your DNS / provider documents. Port 587 (STARTTLS) or 465 (TLS).',
  },
  {
    id: 'ovh',
    kind: 'ovh',
    label: 'OVH Mail',
    host: 'smtp.mail.ovh.net',
    port: 587,
    secure: false,
    hint: 'Username is the full OVH email address. App may need SMTP enabled in the OVH webmail.',
  },
  {
    id: 'ovh-ssl',
    kind: 'ovh',
    label: 'OVH Mail (SSL 465)',
    host: 'ssl0.ovh.net',
    port: 465,
    secure: true,
    hint: 'Alternate OVH endpoint using implicit TLS on 465.',
  },
  {
    id: 'gmail',
    kind: 'webmail',
    label: 'Gmail',
    host: 'smtp.gmail.com',
    port: 587,
    secure: false,
    hint: 'Use an App Password (Google Account → Security). Regular account passwords are blocked.',
  },
  {
    id: 'outlook',
    kind: 'webmail',
    label: 'Outlook / Microsoft 365',
    host: 'smtp.office365.com',
    port: 587,
    secure: false,
    hint: 'Username is the full Microsoft address. SMTP AUTH must be enabled for the mailbox.',
  },
  {
    id: 'yahoo',
    kind: 'webmail',
    label: 'Yahoo Mail',
    host: 'smtp.mail.yahoo.com',
    port: 587,
    secure: false,
    hint: 'Generate an app password in Yahoo Account Security.',
  },
  {
    id: 'icloud',
    kind: 'webmail',
    label: 'iCloud Mail',
    host: 'smtp.mail.me.com',
    port: 587,
    secure: false,
    hint: 'Requires an app-specific password from appleid.apple.com.',
  },
  {
    id: 'zoho',
    kind: 'webmail',
    label: 'Zoho Mail',
    host: 'smtp.zoho.com',
    port: 587,
    secure: false,
    hint: 'Username is the full Zoho address.',
  },
  {
    id: 'yahoo-jp',
    kind: 'japan',
    label: 'Yahoo! Mail Japan',
    host: 'smtp.mail.yahoo.co.jp',
    port: 465,
    secure: true,
    hint: 'Use the Yahoo Japan mailbox and an app password. Send via Yahoo’s official SMTP, not a proxy.',
  },
  {
    id: 'gmail-jp',
    kind: 'japan',
    label: 'Gmail (JP account)',
    host: 'smtp.gmail.com',
    port: 587,
    secure: false,
    hint: 'Same as Gmail: App Password required. Works for googlemail.com / gmail.com JP accounts.',
  },
  {
    id: 'outlook-jp',
    kind: 'japan',
    label: 'Outlook Japan',
    host: 'smtp.office365.com',
    port: 587,
    secure: false,
    hint: 'Microsoft 365 / Outlook.jp mailboxes via official SMTP AUTH.',
  },
  {
    id: 'sakura',
    kind: 'japan',
    label: 'Sakura Internet',
    host: 'initial.sakura.ne.jp',
    port: 587,
    secure: false,
    hint: 'Replace host with your Sakura initial domain if different. Username is the full mail address.',
  },
  {
    id: 'xserver',
    kind: 'japan',
    label: 'Xserver',
    host: 'sv000.xserver.jp',
    port: 587,
    secure: false,
    hint: 'Replace sv000 with your server ID from the Xserver panel (e.g. sv1234.xserver.jp).',
  },
  {
    id: 'lolipop',
    kind: 'japan',
    label: 'Lolipop',
    host: 'smtp.lolipop.jp',
    port: 587,
    secure: false,
    hint: 'Username is the full Lolipop mail address.',
  },
  {
    id: 'gmo',
    kind: 'japan',
    label: 'GMO / ConoHa',
    host: 'mail.lolipop.jp',
    port: 587,
    secure: false,
    hint: 'Check the GMO panel for the exact SMTP host assigned to your contract.',
  },
  {
    id: 'biglobe',
    kind: 'japan',
    label: 'Biglobe',
    host: 'mail.biglobe.ne.jp',
    port: 587,
    secure: false,
    hint: 'Biglobe mail SMTP. Username is usually the full address.',
  },
  {
    id: 'ocn',
    kind: 'japan',
    label: 'OCN Mail',
    host: 'smtp.ocn.ne.jp',
    port: 587,
    secure: false,
    hint: 'OCN mailbox SMTP. Authenticate with the OCN mail account.',
  },
  {
    id: 'office365-smtp',
    kind: 'office365',
    label: 'Microsoft 365 SMTP AUTH',
    host: 'smtp.office365.com',
    port: 587,
    secure: false,
    hint: 'Prefer the Office 365 admin page for tenant Graph apps. SMTP AUTH must be enabled on the mailbox.',
  },
  {
    id: 'smtp-sms',
    kind: 'smtp_sms',
    label: 'SMTP-to-SMS gateway',
    host: '',
    port: 587,
    secure: false,
    hint: 'Sends a short text as email to number@carrier-gateway. Set the gateway domain on the sender (e.g. txt.att.net).',
  },
];

export const SMS_GATEWAYS = [
  { id: 'att', label: 'AT&T', domain: 'txt.att.net' },
  { id: 'tmobile', label: 'T-Mobile', domain: 'tmomail.net' },
  { id: 'verizon', label: 'Verizon', domain: 'vtext.com' },
  { id: 'sprint', label: 'Sprint / Boost', domain: 'messaging.sprintpcs.com' },
  { id: 'uscellular', label: 'U.S. Cellular', domain: 'email.uscc.net' },
  { id: 'googlefi', label: 'Google Fi', domain: 'msg.fi.google.com' },
  { id: 'custom', label: 'Custom domain / pattern', domain: '' },
];

export function presetById(id) {
  return SMTP_PRESETS.find((p) => p.id === id) || null;
}
